### ISSUE TITLE
Where can see button for 2fa in Kirby panel?

### ISSUE THREAD

**Issue by zaicev-maxim** [graphicmarket/kirby-2fa#1]
Hello @rtorresn10,
I am trying 2fa for kirby, but I can't see any button in kirby panel?
Could you please share screenshot for this?
Regards
Maxim

**Comment by rtorresn10** [comment]
Hello @zaicev-maxim,

Have you added the field to the user blueprint?

```yaml
fields:  
  auth:
    type: 2fa
```

Once you has done this, only find this button on the user page:

![Screen Shot 2020-04-23 at 4 49 02 PM](https://user-images.githubusercontent.com/44304163/80153221-c1176500-8582-11ea-9dcb-4639d0f1b795.png)

**Comment by zaicev-maxim** [comment]
@rtorresn10 , thanks so much.
It works well.
